src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private string $firstname;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private string $lastname;

        /**
     * @ORM\Column(type="string", length=255)
     */
    private string $telephone;

    /**
     * @ORM\Column(type="json")
     */
    private ?array $roles = [];

    /**
     * @ORM\OneToOne(targetEntity=Client::class, mappedBy="user", cascade={"persist", "remove"})
     */

    private ?Client $client;

    /**
     * @ORM\OneToOne(targetEntity=Coach::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private ?Coach $coach;

    public const ROLES = [
        'ROLE_SUPERADMIN' => 'Administrateur',
        'ROLE_CLIENT' => 'Client',
        'ROLE_COACH' => 'Coach',
    ];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $client->setUser($this);
        $this->client = $client;

        return $this;
    }

    public function getCoach(): ?Coach
    {
        return $this->coach;
    }

    public function setCoach(Coach $coach): self
    {
        $coach->setUser($this);
        $this->coach = $coach;

        return $this;
    }

    public function getMainRole(): string
    {
        foreach (self::ROLES as $roleCode => $roleLabel) {
            if (in_array($roleCode, $this->getRoles())) {
                return $roleLabel;
            }
        }

        return '';
    }
}

src/Controller/SuperAdminController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Coach;
use App\Form\EditUserType;
use App\Entity\SearchCoach;
use App\Entity\SearchClient;
use App\Form\SearchCoachType;
use App\Form\SearchClientType;
use App\Repository\UserRepository;
use App\Repository\CoachRepository;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/superadmin", name="superadmin_")
 * @isGranted("ROLE_SUPERADMIN")
 */
class SuperAdminController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        return $this->render('super_admin/index.html.twig', [
            'app_controller' => 'SuperAdminController',
        ]);
    }

    /**
     * @Route("/coachs", name="show_coachs")
     */
    public function showCoachs(CoachRepository $coachRepository, Request $request): Response
    {
        $searchCoach = new SearchCoach();
        $form = $this->createForm(SearchCoachType::class, $searchCoach);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $coachs = $coachRepository->findBySearch($searchCoach);
        }
        return $this->render('super_admin/show_coachs.html.twig', [
            'coachs' => $coachs ??  $coachRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/clients", name="show_clients")
     */
    public function showClient(ClientRepository $clientRepository, Request $request): Response
    {
        $searchClient = new SearchClient();
        $form = $this->createForm(SearchClientType::class, $searchClient);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $clients = $clientRepository->findBySearch($searchClient);
        }

        return $this->render('super_admin/show_clients.html.twig', [
            'clients' => $clients ??  $clientRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/utilisateurs", name="show_users")
     */
    public function showUser(UserRepository $users): Response
    {
        return $this->render('super_admin/show_users.html.twig', [
            'users' => $users->findAll(),
        ]);
    }

    /**
     * @Route("/utilisateur/editer/{id}", name="edit_user")
     */
    public function editUser(User $user, Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EditUserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newRole = $form->get('roles')->getData();

            //Si le ROLE_COACH est attribué
            if ($newRole == 'ROLE_COACH') {
                //Si le User n'est pas lié à un coach, je le lie à un nouvel objet coach et je persiste
                if (is_null($user->getCoach())) {
                    $coach = new Coach();
                    $user->setCoach($coach);
                    $entityManager->persist($coach);
                }
            }

            $user->setRoles([$newRole]);
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('success', $form->get('roles')->getData() . ' a bien été attribué à cet utilisateur ');

            return $this->redirectToRoute('superadmin_show_users');
        }
        return $this->render('super_admin/edit_user.html.twig', [
            'userForm' => $form->createView(),
            'user' => $user
        ]);
    }
}

templates/super_admin/edit_user.html.twig
{% extends 'layout_superadmin.html.twig' %}

{% block title %}Attribuer les rôles{% endblock %}

{% block content %}
<div class="container">
    <h1> Attribuer un rôle </h1>
        <div class="border border-dark m-2">
            <div class="profile-h2 d-flex align-items-center bg-dark rounded w-75 p-0">
                <h2 class="m-2 text-light text-truncate"> <i class="bi bi-people-fill text-success"></i> {{ user.firstname }} {{ user.lastname }}</h2>
            </div>
            <div class="container rounded my-3 mx-3">
                <div class="my-3">
                    {{ form_start(userForm) }}
                        {{ form_errors(userForm.roles) }}
                        {{ form_label(userForm.roles, 'Rôles:') }}
                        {{ form_widget(userForm.roles) }}
                        <div class="d-flex justify-content-end">
                            <button class="btn btn-success text-white mx-4"><i class="bi bi-check-square-fill text-white"></i> {{ button_label|default('Valider') }}</button>
                        </div>
                    {{ form_end(userForm) }}
                </div>
            </div>
        </div>
    <div class="d-flex justify-content-end">
        <p class= "text-uppercase fw-bold fst-italic"><a href="{{ path('superadmin_show_users') }}" class="btn btn-success text-dark"><i class="bi bi-arrow-counterclockwise text-dark"></i> Retour liste utilisateurs</a></p>
    </div>
</div>
{% endblock %}

templates/super_admin/index.html.twig
{% extends 'layout_superadmin.html.twig' %}

{% block title %}Hello {{ app.user.firstname }} !{% endblock %}

{% block content %}
<main class="col-md-10 mx-auto my-5">
    <h1>✅ Bonjour {{ app.user.firstname }} !</h1>

    <div class="row">
        <div class="col-6 d-flex justify-content-center">
            <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('superadmin_show_users') }}" class="btn text-success"><i class="bi bi-people-fill text-success"></i> Gérer les utilisateurs</a>
                    </div>
                    <p class="card-text text-light">Consulter la liste des utilisateurs, éditer et attribuer les
                        rôles (ex : ajouter ou supprimer un coach).</p>
                </div>
            </div>
        </div>
        <div class="col-6 d-flex justify-content-center">
            <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('superadmin_show_clients') }}" class="btn text-success"><i class="bi bi-file-earmark-person-fill text-success"></i> Gérer les clients</a>
                    </div>
                    <p class="card-text text-light">Consulter la liste des clients.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 d-flex justify-content-center">
            <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('superadmin_show_coachs') }}" class="btn text-success"> <i class="bi bi-trophy-fill text-success"></i> Gérer les coachs</a>
                    </div>
                <p class="card-text text-light">Consulter la liste des coachs.</p>
                </div>
            </div>
        </div>
        <div class="col-6 d-flex justify-content-center">
            <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('admin_activity_index') }}" class="btn text-success"><i class="bi bi-palette2 text-success"></i> Gérer les activités</a>
                    </div>
                <p class="card-text text-light">Consulter la liste des activités, éditer et supprimer.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 d-flex justify-content-center">
        <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('admin_space_index') }}" class="btn text-success"><i class="bi bi-geo-alt-fill text-success"></i> Gérer les espaces d'entrainement</a>
                    </div>
                <p class="card-text text-light">Consulter la liste des espaces d'entrainement, ajouter, éditer et supprimer.</p>
                </div>
            </div>
        </div>
        <div class="col-6 d-flex justify-content-center">
            <div class="space-card my-3 m-auto border border-dark bg-dark rounded w-75">
                <div class="card-body">
                    <div class="d-flex justify-content-start">
                        <a href="{{ path('coach_booking_index') }}" class="btn text-success"><i class="bi bi-journal-richtext text-success"></i> Gérer les réservations</a>
                    </div>
                    <p class="card-text text-light">Consulter la liste des réservations de coach, attribuer les coachs et
                        les espaces.</p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/super_admin/show_clients.html.twig
{% extends 'layout_superadmin.html.twig' %}

{% block title %}
  Clients
{% endblock %}

{% block content %}

    <h1 class="my-5">
      Gérer les Clients
    </h1>
    <div class="row mt-2 mb-2">
        <div class="col-10"><i class="bi bi-exclamation-circle-fill"></i> Recherche par nom ou prénom :
        </div>
    </div>
    <div class="row mt-2 mb-2">
        <div class="col-6">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        </div>
        <div class="col-4">
          <button class="btn btn-success text-white"><i class="bi bi-search text-white"></i> Rechercher</button>
          {{ form_end(form) }}
        </div>
    </div>
    <table class="table table-striped text-center bg-light mt-5">
      <thead>
        <tr>
          <th scope="col" class=" bg-dark text-white">
            Client
          </th>
          <th scope="col" class=" bg-dark text-white">
            Date de naissance
          </th>
          <th scope="col" class=" bg-dark text-white">
            Activité
          </th>
          <th scope="col" class=" bg-dark text-white">
            Contact
          </th>
          <th scope="col" class=" bg-dark text-white">
            Coach
          </th>
        </tr>
      </thead>
      <tbody>
        {% for client in clients %}
          <tr>
            <td>
              {{ client.user.firstname }} {{ client.user.lastname }}
            </td>
            <td>
              {{ client.birthdate|date("d/m/Y") }}
            </td>
            {% if client.activity is not null %}
            <td>
                {{ client.activity.name }}
              </td>
            {% else %}
              <td>
                Aucune
            </td>
            {% endif %}
            <td>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ client.user.email }} </li>
                <li class="list-group-item">{{ client.user.telephone }} </li>
              </ul>
            </td>
            {% if client.coachbooking is null or client.coachbooking.coach is null %}
              <td class = "fw-bold">
                Aucun coach
              </td>
            {% else %}
              <td>
                {{ client.coachbooking.coach.user.firstname }}
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="d-flex justify-content-end">
      <p class= "text-uppercase fw-bold fst-italic"><a href="{{ path('superadmin_index') }}" class="btn btn-success text-dark"><i class="bi bi-arrow-counterclockwise text-dark"></i> Retour espace admin</a></p>
    </div>
    {% block javascripts %}
      {{ encore_entry_script_tags('app') }}
    {% endblock %}
{% endblock %}

templates/super_admin/show_coachs.html.twig
{% extends 'layout_superadmin.html.twig' %}

{% block title %}Coachs{% endblock %}

{% block content %}

    <h1 class="my-5">Gérer les Coachs</h1>

    <div class="row mt-2 mb-2">
        <div class="col-4 mx-1"><i class="bi bi-exclamation-circle-fill"></i> Recherche par nom ou prénom : </div>
        <div class="col-4"><i class="bi bi-palette2"></i> Recherche par activité : </div>
    </div>
    <div class="row mt-2 mb-2">
        <div class="col-4">
            {{ form_start(form) }}
            {{ form_row(form.user) }}
        </div>
        <div class="col-4">
            {{ form_row(form.activity) }}
        </div>
        <div class="col-4">
            <button class="btn btn-success text-white"><i class="bi bi-search text-white"></i> Rechercher</button>
            {{ form_end(form) }}
        </div>
    </div>

    <table class="table table-striped text-left text-center bg-light mt-5">
        <thead>
            <tr>
                <th scope="col" class=" bg-dark text-white">Coach</th>
                <th scope="col" class=" bg-dark text-white">Activité</th>
                <th scope="col" class=" bg-dark text-white">Tarif</th>
                <th scope="col" class=" bg-dark text-white">Disponibilité</th>
                <th scope="col" class=" bg-dark text-white">Client</th>
            </tr>
        </thead>
        <tbody>
            {% for coach in coachs %}
                <tr class="align-middle">
                    <td>{{ coach.user.firstname }} {{ coach.user.lastname }}</td>
                    <td>
                        <ul class="list-group list-group-flush">
                            {% for activity in coach.activities %}
                                <li class="list-group-item">{{ activity.name }}</li>
                            {% else %}
                                Aucune activité
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ coach.hourlyrate }} €</td>
                    <td>
                        {% for availability in coach.availabilities %}
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ availability.weekday.name }} {{ availability.startTime|format_time('short') }} - {{ availability.endTime|format_time('short') }} </li>
                        </ul>
                        {% endfor %}
                    </td>
                    <td>
                    {% if coach.coachBookings is empty %}
                         Aucun client
                    {% else %}
                        {% for booking in coach.coachBookings %}
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"> {{ booking.client.user.firstname }} {{ booking.client.user.lastname }}</li>
                            </ul>
                        {% endfor %}
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-end">
        <p class= "text-uppercase fw-bold fst-italic"><a href="{{ path('superadmin_index') }}" class="btn btn-success text-dark"><i class="bi bi-arrow-counterclockwise text-dark"></i> Retour espace admin</a></p>
    </div>
{% endblock %}

templates/super_admin/show_users.html.twig
{% extends 'layout_superadmin.html.twig' %}

{% block title %}Utilisateurs
{% endblock %}

{% block content %}
<div class="container">
	<h1>Gérer les utilisateurs</h1>

	<table class="table table-striped text-center bg-light">
		<thead>
			<tr>
				<th class="bg-dark text-white">Email</th>
				<th class="bg-dark text-white">Nom</th>
				<th class="bg-dark text-white">Telephone</th>
				<th class="bg-dark text-white">Roles</th>
				<th class="bg-dark text-white">Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ user.email }}</td>
					<td>{{ user.firstname }}
						{{ user.lastname }}</td>
					<td>{{ user.telephone }}</td>
					<td>
                        {{ user.mainRole }}
					</td>
					<td>
						<a href="{{ path('superadmin_edit_user', {'id': user.id}) }}" class="btn btn-success text-light fs-6"><i class="bi bi-pencil-square text-white me-2"></i> Éditer</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="8">Aucun utilisateur trouvé</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<div class="text-uppercase fw-bold fst-italic d-flex justify-content-end">
		<a href="{{ path('superadmin_index') }}" class="btn btn-success text-dark"><i class="bi bi-arrow-counterclockwise text-dark"></i> Retour espace admin</a>
	</div>
</div>
{% endblock %}